import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import VersionLogger from "@/components/version-logger";
import { Toaster } from "sonner";

const fontTanker = localFont({
  src: "./assets/fonts/Tanker-Regular.woff2",
  variable: "--font-tanker",
})

const spaceGotestk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nebula",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGotestk.variable} ${fontTanker.variable} antialiased`}
      >
        <VersionLogger />
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: 'rgb(27, 28, 34)',
              border: '1px solid rgba(137, 166, 251, 0.2)',
              color: 'rgb(220, 222, 241)',
              fontFamily: 'var(--font-space-grotesk)',
            },
          }}
        />
      </body>
    </html>
  );
}
