import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const fontTanker = localFont({
  src: "./assets/fonts/Tanker-Regular.woff2",
  variable: "--font-tanker",
})

const spaceGotestk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nebula",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGotestk.variable} ${fontTanker.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
