import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import VersionLogger from "@/components/version-logger";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/app/context/theme-context";

const fontTanker = localFont({
  src: "./assets/fonts/Tanker-Regular.woff2",
  variable: "--font-tanker",
})

const spaceGotestk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nebula",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGotestk.variable} ${fontTanker.variable} antialiased`}
      >
        <ThemeProvider>
          <VersionLogger />
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: 'var(--card)',
                border: '1px solid var(--border)',
                color: 'var(--card-foreground)',
                fontFamily: 'var(--font-space-grotesk)',
              },
              className: 'font-space-grotesk',
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
